spring:
  application:
    name: travel2china
  freemarker:
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/
    cache: false
    content-type: text/html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

mybatis-plus:
  type-aliases-package: com.gklx.travel.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
